services:
  db:
    image: postgres:16-alpine
    container_name: models-library-database
    environment:
      - POSTGRES_DB=ModelsDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "ModelsDB", "-U", "user" ]
      start_period: 5s
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    build: ./ModelsLibrary
    container_name: models-library
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./ModelsLibraryFront
    container_name: models-library-frontend
    ports:
      - "8081:80"
    depends_on:
      backend:
        condition: service_started
volumes:
  pg:
